### PR TITLE
Updated Login Flow as requested 

### PR DESCRIPTION
**Pull request by nervehammer**
New API path is used supports login function only

### CODE REVIEW

**Comment by imujjwal96** [comment]
Why does this PR have so many commits?

**Comment by imujjwal96** [comment]
Allow me to walk you through this!
Follow the following steps
In your repository, drop the commits `Latest server documentation file` and `Squashed raw/server .....`
To do this, type

    git rebase -i HEAD~20

Find the commits and drop them.
index

Then run the commands

    git remote add upstream https://github.com/BrimeNotes/android.git
    git pull --upstream master
    git push origin +master

**Comment by nervehammer** [comment]
@imujjwal96 check now looks good to me :P

**Comment by imujjwal96** [comment]
@syedsaadh Please review.

**Comment by syedsaadh** [comment]
1. I would suggest to used ***VolleySingleton*** Class for handling all the RequestQueues. This will help in creating Multiple Requests will single Request Queue instance.
[Check this answer for more details](https://stackoverflow.com/a/43234645)

2. Make a Class for Account Setup in Shared Preferences. This helps in making code clean and Also in having reusable code.
[You can get idea here](https://gist.github.com/syedsaadh/7f79e24c764f9c8a317ffbdc565dc0da)

**Comment by syedsaadh** [comment]
I m merging the PR and then you can send another PR with refactored code

**Pull request merged**
